kind: Service
apiVersion: v1
metadata:
  name: efa-frontend-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 3000
      port: 80
      nodePort: 30001
  selector:
    app: efa
    tier: frontend
