kind: Service
apiVersion: v1
metadata:
  name: efa-frontend-service
spec:
  type: NodePort
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30001
  selector:
    app: efa
    tier: frontend
